preload = /home/dallon/storage/Изображения/1711580718.caraid_baskingcapybara_signature.jpg
preload = /home/dallon/storage/Изображения/Saved Pictures/1487029488.wolnir_hunter6_copy4sm.png

wallpaper {
    monitor = HDMI-A-1
    path = /home/dallon/storage/Изображения/1711580718.caraid_baskingcapybara_signature.jpg
    fit_mode = fill
}

wallpaper {
    monitor = DP-3
    path = /home/dallon/storage/Изображения/Saved Pictures/1487029488.wolnir_hunter6_copy4sm.png
    fit_mode = fill
}
