#адрес обоев
preload = ~/.config/hypr/wallpapers/paws-placeholder.png

# Пустое поле monitor -> обои применяются ко ВСЕМ подключённым мониторам,
# можно выбрать определенные, выбор можно посмотреть в 
#                       hyprctl monitors
#например DP-3, HDMI-A-1,
wallpaper {
    monitor = 
    path = ~/.config/hypr/wallpapers/paws-placeholder.png
    fit_mode = tile #tile, fill, contain, cover
}

